name: Run check scripts

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyang requests

      - name: Run check scripts
        run: |
          ./vendor/fujitsu/yang-validate.sh
          ./vendor/cisco/check.sh
          ./standard/ietf/check.sh
          ./standard/bbf/check.sh
          ./experimental/ieee/check.sh
          ./standard/ieee/check.sh
